// <auto-generated />
namespace Publishing.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DatabaseGeneratedDatabaseGeneratedOptionComputed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DatabaseGeneratedDatabaseGeneratedOptionComputed));
        
        string IMigrationMetadata.Id
        {
            get { return "201804201648315_[DatabaseGenerated(DatabaseGeneratedOption.Computed)]"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
